### ISSUE TITLE
Error saving the model: scala.NotImplementedError: The default jsonEncode only supports string, vector and matrix. org.apache.spark.ml.param.Param must override jsonEncode for java.lang.Double.

### ISSUE THREAD

**Issue by spicoflorin** [titicaca/spark-iforest#15]
Hi!
 I would like to save the obtained model with the code
`  model.write.overwrite().save("myisolatedforestmodel")`
but I bumped into the error:
scala.NotImplementedError: The default jsonEncode only supports string, vector and matrix. org.apache.spark.ml.param.Param must override jsonEncode for java.lang.Double.
Can you please check what is the issue?

**Comment by titicaca** [comment]
Thanks for reporting it. It was caused by an incorrect param type in last updates. I have just fixed it. Pull the latest codes and try again.
