### ISSUE TITLE
Does the model training need labeled data? 

### ISSUE THREAD

**Issue by DanyYan** [titicaca/spark-iforest#16]
I find the example need to set the label column, so can't this model be used for unlabeled data?

**Comment by titicaca** [comment]
Label column is only for evaluation in the example codes. The algorithm is unsupervised, thus you don't need to set the label column for model fitting.

**Comment by DanyYan** [comment]
hello, I have another problem.If I use unlabeled data to train, how can I evaluate the model？

**Comment by titicaca** [comment]
You cannot evaluate the model without labeled data, the algorithm is unsupervised and only detects isolated data in its way, but you don't know which is the real isolated data without labels.

**Comment by DanyYan** [comment]
ok, so does the lable 1 means the isolated data?

**Comment by titicaca** [comment]
yes

**Comment by DanyYan** [comment]
ok,thank you.
