### ISSUE TITLE
backward (Spark) support

### ISSUE THREAD

**Issue by pmarko1711** [titicaca/spark-iforest#17]
In my environment I sadly cannot upgrade Spark, and we're still at 2.2.0. It takes lots of hacks to get the library running with pyspark and `approxQuantileRelativeError` (both features added only with the library upgrade to 2.4). 

I wonder whether it would be difficult to keep the library somehow backward compatible and support also few older Spark versions.

**Comment by titicaca** [comment]
You can try to make the jar package with the prev version 2.2.0
 https://github.com/titicaca/spark-iforest/releases/tag/v2.2.0

**Comment by pmarko1711** [comment]
Thanks and yes, that's what I'm in the end doing, but have to add approximate quantile and the python wrapper. I understand Spark 2.4 changed some of its API, and I'm not sure how easy it is to keep the library supporting both the new and old calls. I myself would only add it if it was super easy. Feel free to close it if that's not the case or if you simply don't want to add it. I can keep my own forked version somewhere until we upgrade to Spark 2.4

**Comment by titicaca** [comment]
As I remember, some spark api are not compatible for these two different versions. 

Maybe it is easier to modify the incompatible python wrapper methods in python lib for spark v2.2.0.
