### ISSUE TITLE
Regarding ApproxQuantile

### ISSUE THREAD

**Issue by tahmedge** [titicaca/spark-iforest#20]
Can you please tell me what is the purpose of  "ApproxQuantile"? I could not find it in sklearn implementation of the iForest algorithm. Also, I can't find (or I may have missed) it in the paper. the value of ApproxQuantile was giving GCoverhead error in my large dataset (130 millions of examples). Now I set it to 0.5, and it was running successfully. But I am confused what happens for setting the value to 0.5? Can you please tell?

**Comment by titicaca** [comment]
You can set this param approxQuantileRelativeError, which is the Relative Error for Approximate Quantile Calculation (0 <= value <= 1), default is 0 for calculating the exact value, which would be expensive for large datasets.

**Comment by titicaca** [comment]
Furthermore, ApproxQuantile is used to calculating the threshold of anomaly score for finding anomaly points according to the given param contamination. Regarding ApproxQuantile function, you can find more detail in the spark api doc:

https://spark.apache.org/docs/latest/api/python/_modules/pyspark/sql/dataframe.html#DataFrame.approxQuantile

**Comment by tahmedge** [comment]
Hi, thanks for your reply. I am still bit confused. 

Suppose, the contamination value is 0.1 . In this case, what could be the best value for ApproxQuantile ?

**Comment by titicaca** [comment]
It depends on what the relative error of the quantile value you can accept. The smaller the relative error is, the more expensive and more memory required for calculation. You can try with different values from small to large, so that it can fit your memory consume.

**Comment by tahmedge** [comment]
Thanks a lot.
