### ISSUE TITLE
error: object DefaultParamsWriter in package util cannot be accessed in package org.apache.spark.ml.util

### ISSUE THREAD

**Issue by Berwin77** [titicaca/spark-iforest#23]
error: object DefaultParamsWriter in package util cannot be accessed in package org.apache.spark.ml.util

**Comment by titicaca** [comment]
make sure ur spark version is 2.4.x

**Comment by Berwin77** [comment]
thank you ! my project spark version is 2.3! if u have history code to adaptade 2.3? thank you very much!!

**Comment by titicaca** [comment]
Check the release tag: https://github.com/titicaca/spark-iforest/releases/tag/v2.3.0, you can build and use the jar pkg. 

However, if you want to use python api,  you have to use  spark 2.4.x.  The python pkg currently is not compatible with the old versions.

**Comment by Berwin77** [comment]
thank you very much ！！ woderful！
