### ISSUE TITLE
our spark version is 2.2.0, what can i do?

### ISSUE THREAD

**Issue by flybird101** [titicaca/spark-iforest#25]
can i change the <spark.version>2.4.0</spark.version> of the pom file into <spark.version>2.2.0</spark.version>

**Comment by flybird101** [comment]
> can i change the <spark.version>2.4.0</spark.version> of the pom file into <spark.version>2.2.0</spark.version>

---it's not work.

**Comment by titicaca** [comment]
It won't work, because it uses different APIs. You can find v2.2.0 in the releases: https://github.com/titicaca/spark-iforest/releases. 

By the way, pyspark-iforest is only supported on v2.4.x.

**Comment by flybird101** [comment]
> It won't work, because it uses different APIs. You can find v2.2.0 in the releases: https://github.com/titicaca/spark-iforest/releases.
> 
> By the way, pyspark-iforest is only supported on v2.4.x.

ok, thanks.
