### ISSUE TITLE
Data type StringType is not supported.

### ISSUE THREAD

**Issue by flybird101** [titicaca/spark-iforest#26]
**dataset.show  //my data like this**
+-------+---+---+---+---+---+---+---+---+---+----+
|    _c0|_c1|_c2|_c3|_c4|_c5|_c6|_c7|_c8|_c9|_c10|
+-------+---+---+---+---+---+---+---+---+---+----+
|1000025|  5|  1|  1|  1|  2|  1|  3|  1|  1|   2|
|1002945|  5|  4|  4|  5|  7| 10|  3|  2|  1|   2|
|1015425|  3|  1|  1|  1|  2|  2|  3|  1|  1|   2|
|1016277|  6|  8|  8|  1|  3|  4|  3|  7|  1|   2|
|1017023|  4|  1|  1|  3|  2|  1|  3|  1|  1|   2|
|1017122|  8| 10| 10|  8|  7| 10|  9|  7|  1|   4|
|1018099|  1|  1|  1|  1|  2| 10|  3|  1|  1|   2|
|1018561|  2|  1|  2|  1|  2|  1|  3|  1|  1|   2|
|1033078|  2|  1|  1|  1|  2|  1|  1|  1|  5|   2|
|1033078|  4|  2|  1|  1|  2|  1|  2|  1|  1|   2|
|1035283|  1|  1|  1|  1|  1|  1|  3|  1|  1|   2|
|1036172|  2|  1|  1|  1|  2|  1|  2|  1|  1|   2|
|1041801|  5|  3|  3|  3|  2|  3|  4|  4|  1|   4|
|1043999|  1|  1|  1|  1|  2|  3|  3|  1|  1|   2|
|1044572|  8|  7|  5| 10|  7|  9|  5|  5|  4|   4|
|1047630|  7|  4|  6|  4|  6|  1|  4|  3|  1|   4|
|1048672|  4|  1|  1|  1|  2|  1|  2|  1|  1|   2|
|1049815|  4|  1|  1|  1|  2|  1|  3|  1|  1|   2|
|1050670| 10|  7|  7|  6|  4| 10|  4|  1|  2|   4|
|1050718|  6|  1|  1|  1|  2|  1|  3|  1|  1|   2|
+-------+---+---+---+---+---+---+---+---+---+----+
only showing top 20 rows

**//when I run those code...**
val pipeline = new Pipeline().setStages(Array(indexer, assembler, iForest))
val model = pipeline.fit(dataset)
val predictions = model.transform(dataset)

Name: java.lang.IllegalArgumentException
Message: Data type StringType is not supported.
StackTrace:   at org.apache.spark.ml.feature.VectorAssembler$$anonfun$transformSchema$1.apply(VectorAssembler.scala:121)
  at org.apache.spark.ml.feature.VectorAssembler$$anonfun$transformSchema$1.apply(VectorAssembler.scala:117)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at org.apache.spark.ml.feature.VectorAssembler.transformSchema(VectorAssembler.scala:117)
  at org.apache.spark.ml.Pipeline$$anonfun$transformSchema$4.apply(Pipeline.scala:184)
  at org.apache.spark.ml.Pipeline$$anonfun$transformSchema$4.apply(Pipeline.scala:184)
  at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
  at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
  at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
  at org.apache.spark.ml.Pipeline.transformSchema(Pipeline.scala:184)
  at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:74)
  at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:136)

//My data not have the string type。。。

**Comment by flybird101** [comment]
val spark = SparkSession
.builder()
.master("local") // test in local mode
.appName("iforest example")
.getOrCreate()

val startTime = System.currentTimeMillis()

// Wisconsin Breast Cancer Dataset
val dataset = spark.read.option("inferSchema", "true")
.csv("kevin/breast.csv")

dataset.show
dataset.printSchema

// Index label values: 2 -> 0, 4 -> 1
import org.apache.spark.ml.feature.StringIndexer
val indexer = new StringIndexer()
.setInputCol("_c10")
.setOutputCol("label")

indexer.getInputCol

import org.apache.spark.ml.feature.VectorAssembler
val assembler = new VectorAssembler()
assembler.setInputCols(Array("_c1", "_c2", "_c3", "_c4", "_c5", "_c6", "_c7", "_c8", "_c9"))
assembler.setOutputCol("features")

import org.apache.spark.ml.iforest._

val iForest = new IForest()
.setNumTrees(100)
.setMaxSamples(256)
.setContamination(0.35)
.setBootstrap(false)
.setMaxDepth(100)
.setSeed(123456L)

import org.apache.spark.ml.{Pipeline, PipelineModel} 
val pipeline = new Pipeline().setStages(Array(indexer, assembler, iForest))
val model = pipeline.fit(dataset)  **//the error happen**

**Comment by titicaca** [comment]
IForest doesn't support string type as features. You can convert it either to integer by StringIndexer, or you can use one hot encoding by OnehotEncoder.

**Comment by flybird101** [comment]
> IForest doesn't support string type as features. You can convert it either to integer by StringIndexer, or you can use one hot encoding by OnehotEncoder.

But，my features all not string type.

dataset.printSchema
root
 |-- _c0: integer (nullable = true)
 |-- _c1: integer (nullable = true)
 |-- _c2: integer (nullable = true)
 |-- _c3: integer (nullable = true)
 |-- _c4: integer (nullable = true)
 |-- _c5: integer (nullable = true)
 |-- _c6: string (nullable = true)
 |-- _c7: integer (nullable = true)
 |-- _c8: integer (nullable = true)
 |-- _c9: integer (nullable = true)
 |-- _c10: integer (nullable = true)

**Comment by titicaca** [comment]
maybe you can check column _c6?

**Comment by flybird101** [comment]
> maybe you can check column _c6?

Oh！Yes！I hadn't find it. Thanks!
