### ISSUE TITLE
Error while initializing the model

### ISSUE THREAD

**Issue by vvenugopsfu** [titicaca/spark-iforest#28]
I have followed the instructions and successfully installed all the requirements. But I am unable initialize the model

from pyspark_iforest.ml.iforest import *

# Init an IForest Object
iforest = IForest(contamination=0.3, maxDepth=2)

error:
-----------------------------------------------------------
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-11-f846215e10eb> in <module>
      2 
      3 # Init an IForest Object
----> 4 iforest = IForest(contamination=0.3, maxDepth=2)

~/spark-3.0.0-preview2-bin-hadoop2.7/python/pyspark/__init__.py in wrapper(self, *args, **kwargs)
    109             raise TypeError("Method %s forces keyword arguments." % func.__name__)
    110         self._input_kwargs = kwargs
--> 111         return func(self, **kwargs)
    112     return wrapper
    113 

~/opt/anaconda3/lib/python3.7/site-packages/pyspark_iforest/ml/iforest.py in __init__(self, featuresCol, predictionCol, anomalyScore, numTrees, maxSamples, maxFeatures, maxDepth, contamination, bootstrap, approxQuantileRelativeError)
    243 
    244         super(IForest, self).__init__()
--> 245         self._java_obj = self._new_java_obj("org.apache.spark.ml.iforest.IForest", self.uid)
    246         self._setDefault(numTrees=100, maxSamples=1.0, maxFeatures=1.0, maxDepth=10, contamination=0.1,
    247                          bootstrap=False, approxQuantileRelativeError=0.)

~/spark-3.0.0-preview2-bin-hadoop2.7/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     67             java_obj = getattr(java_obj, name)
     68         java_args = [_py2java(sc, arg) for arg in args]
---> 69         return java_obj(*java_args)
     70 
     71     @staticmethod

~/spark-3.0.0-preview2-bin-hadoop2.7/python/lib/py4j-0.10.8.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1552         answer = self._gateway_client.send_command(command)
   1553         return_value = get_return_value(
-> 1554             answer, self._gateway_client, None, self._fqn)
   1555 
   1556         for temp_arg in temp_args:

~/spark-3.0.0-preview2-bin-hadoop2.7/python/pyspark/sql/utils.py in deco(*a, **kw)
     96     def deco(*a, **kw):
     97         try:
---> 98             return f(*a, **kw)
     99         except py4j.protocol.Py4JJavaError as e:
    100             converted = convert_exception(e.java_exception)

~/spark-3.0.0-preview2-bin-hadoop2.7/python/lib/py4j-0.10.8.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling None.org.apache.spark.ml.iforest.IForest.
: java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class
	at org.apache.spark.ml.iforest.IForest.<init>(IForest.scala:335)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by titicaca** [comment]
spark 3.0 are not supported currently. You can try with spark 2.4

**Comment by vvenugopsfu** [comment]
Thank you
