### ISSUE TITLE
有Spark集群测试数据吗？

### ISSUE THREAD

**Issue by 6high** [titicaca/spark-iforest#3]
readme中的测试数据是spark本地多核模式下的，请问有小集群的测试数据吗？

**Comment by titicaca** [comment]
测试是在Spark集群上完成的，测试数据均为公开数据集，可参考论文自行在网上下载

**Comment by 6high** [comment]
请问你的测试集群是什么规模的？ 配置可以说明一下吗？

**Comment by titicaca** [comment]
4台物理机千兆带宽， 资源是yarn上分配的，CPU和内存可参见 https://github.com/titicaca/spark-iforest#benchmark
