### ISSUE TITLE
Pyspark Streaming Iforest

### ISSUE THREAD

**Issue by ayushagg1306** [titicaca/spark-iforest#30]
Error in loading model using PipelineModel.load() in Pyspark.

model = PipelineModel.load(path_to_model)
Traceback (most recent call last):                                              
  File "<stdin>", line 1, in <module>
  File "/home/users/spark-2.4.6-bin-hadoop2.7/python/pyspark/ml/util.py", line 362, in load
    return cls.read().load(path)
  File "/home/users/spark-2.4.6-bin-hadoop2.7/python/pyspark/ml/pipeline.py", line 242, in load
    return JavaMLReader(self.cls).load(path)
  File "/home/users/spark-2.4.6-bin-hadoop2.7/python/pyspark/ml/util.py", line 304, in load
    return self._clazz._from_java(java_obj)
  File "/home/users/spark-2.4.6-bin-hadoop2.7/python/pyspark/ml/pipeline.py", line 299, in _from_java
    py_stages = [JavaParams._from_java(s) for s in java_stage.stages()]
  File "/home/users/spark-2.4.6-bin-hadoop2.7/python/pyspark/ml/pipeline.py", line 299, in <listcomp>
    py_stages = [JavaParams._from_java(s) for s in java_stage.stages()]
  File "/home/users/spark-2.4.6-bin-hadoop2.7/python/pyspark/ml/wrapper.py", line 227, in _from_java
    py_type = __get_class(stage_name)
  File "/home/users/spark-2.4.6-bin-hadoop2.7/python/pyspark/ml/wrapper.py", line 221, in __get_class
    m = __import__(module)
ModuleNotFoundError: No module named 'pyspark.ml.iforest'

**Comment by titicaca** [comment]
Did you install the python package in your python environment? 

You can follow the guide to install the pyspark-iforest package:
https://github.com/titicaca/spark-iforest/blob/master/python/README.md

**Comment by ayushagg1306** [comment]
Yes i have installed the package as in the guide.
And after that copied the jar file into the spark/jar folder.
The PipelineModel.load() is working in scala but giving error in Pyspark, so I think package has been installed correctly.
Please help me with this because I don't want to switch to scala just because of load model error.

**Comment by titicaca** [comment]
The log showed `ModuleNotFoundError: No module named 'pyspark.ml.iforest'`

but the correct module name should be `pyspark_iforest.ml.iforest`. 

You need to use the loading function  in iforest class shown in the example codes instead of using `PipelineModel.load()` , because `PipelineModel.load()` looks into `pyspark.ml` name space.

**Comment by ayushagg1306** [comment]
I want to use isolation forest model in spark Structured Streaming, for that I have to load model in a Pipeline.
It is working in scala, can it be done in Pyspark?

**Comment by titicaca** [comment]
I think it could work, but need some tricks, because `PipelineModel.load()` looks into pyspark.ml path for searching packages only.  The tricks I did in the loading function in pyspark is to rewrite the java_loader_class function to replace the default module name `org.apache.spark` into the package name. You can try to rewrite the PipelineModel.load function in your environment


```
class CustomizedJavaMLReader(JavaMLReader):
    @classmethod
    def _java_loader_class(cls, clazz):
        """
        Returns the full class name of the Java ML instance. The default
        implementation replaces "pyspark" by "org.apache.spark" in
        the Python full class name.
        """
        java_package = clazz.__module__.replace("pyspark_iforest", "org.apache.spark")
        if clazz.__name__ in ("Pipeline", "PipelineModel"):
            # Remove the last package name "pipeline" for Pipeline and PipelineModel.
            java_package = ".".join(java_package.split(".")[0:-1])
        return java_package + "." + clazz.__name__

    def load(self, path):
        """Load the ML instance from the input path."""
        if not isinstance(path, basestring):
            raise TypeError("path should be a basestring, got type %s" % type(path))
        java_obj = self._jread.load(path)
        if not hasattr(self._clazz, "_from_java"):
            raise NotImplementedError("This Java ML type cannot be loaded into Python currently: %r"
                                      % self._clazz)
        return customized_from_java(java_obj)
```
