### ISSUE TITLE
The library doesn't work with Spark 3.0.0

### ISSUE THREAD

**Issue by e-compagno** [titicaca/spark-iforest#31]
Apparently the package doesn't work with Spark 3.0.0, as depends on a older version of Hadoop and Spark, as pointed out in https://survival8.blogspot.com/p/isolation-forest-implementation-using.html. 

The error I receive (An error occurred while calling None.org.apache.spark.ml.iforest.IForest.) after compiling the jar file and install the python version via pip can be obtained running 

```
from pyspark_iforest.ml.iforest import *
 IForest(contamination=0.3, maxDepth=2)
```

Is there any plan to update the library so that it works also with spark 3?

**Comment by titicaca** [comment]
Yes, currently the codes are not available for Spark 3.0, because some apis are changed. I will work on the updates when I find some time in the near future.

**Comment by e-compagno** [comment]
Anyhow, I have tested that the library works with pyspark 2.4.5 and 2.4.7. May I suggest to relax the pyspark version in the library from `pyspark==2.4.0` to `pyspark>=2.4.0,<=2.4.7` to avoid forcing a version downgrade?

**Comment by JJorczik** [comment]
> Yes, currently the codes are not available for Spark 3.0, because some apis are changed. I will work on the updates when I find some time in the near future.

Is there any status update for Spark 3.0 support?

**Comment by titicaca** [comment]
I'm working on it. I just added a new branch https://github.com/titicaca/spark-iforest/tree/spark3 , you can try it with spark 3.0

**Comment by JJorczik** [comment]
> I'm working on it. I just added a new branch https://github.com/titicaca/spark-iforest/tree/spark3 , you can try it with spark 3.0

Seems to work. Thank you!
