### ISSUE TITLE
Compile for Pyspark 3.x.x

### ISSUE THREAD

**Issue by diogoribeiro09** [titicaca/spark-iforest#35]
Hi,
I've used your package on Pyspark 2.4.0 and it works amazing. Thank you for your incredible work.
Due to some project constrains I now need to use Pyspark 3.x.x, . Is this even possible? If so, how should i proceed?

Best Regards,
Diogo Ribeiro

**Comment by titicaca** [comment]
You can try branch spark3, https://github.com/titicaca/spark-iforest/tree/spark3

**Comment by diogoribeiro09** [comment]
Thank you . It works :)
