### ISSUE TITLE
Any update plan for Spark 2.4?

### ISSUE THREAD

**Issue by richardxy** [titicaca/spark-iforest#4]
Hi, 

There are several API changes in Spark 2.4 which break this package. Do you have a plan for version update?

thanks,
Richard

**Comment by titicaca** [comment]
It has been already updated to spark 2.4.0. Check the latest codes in the master branch or the corresponding release tag.

**Comment by richardxy** [comment]
That's great! Thanks. 
Would it be possible if you can document how to install the package and use it in Spark? That would help a lot for users with a different level of experience with Scala/Spark. Currently, it only includes how to import the package and call the APIs. 

Thanks for your work!

Richard

**Comment by titicaca** [comment]
That depends on what you gonna to do with this package. You can just install this package into your maven repository and use it in other projects. Or you can put the package jar into your spark class lib and call it on spark client.
