### ISSUE TITLE
No version for spark1.x

### ISSUE THREAD

**Issue by lurongjiang** [titicaca/spark-iforest#44]
I am attempting to modify the code to be compatible with Spark 1.5, but I have discovered that many of the classes are features of Spark 2.x. Is there a plan to provide a version for Spark 1.x?

**Comment by titicaca** [comment]
Unfortunately there is no plan to support spark 1.x, but I think you can just refactor the codes and change the corresponding classes to the older version.

**Comment by mtsol** [comment]
Do you have support for spark 3.1.1????

**Comment by lurongjiang** [comment]
> 

Not yet, I just copy some code from Spark2.x for Spark1.5 adaptation, not for Spark3.x
