### ISSUE TITLE
load model

### ISSUE THREAD

**Issue by pham-cao** [titicaca/spark-iforest#45]
/usr/local/spark/python/pyspark/ml/wrapper.py in _new_java_obj(java_class, *args)
     65             java_obj = getattr(java_obj, name)
     66         java_args = [_py2java(sc, arg) for arg in args]
---> 67         return java_obj(*java_args)
     68 
     69     @staticmethod

TypeError: 'JavaPackage' object is not callable

**Comment by YanChuan1** [comment]
I met the same error. have you solved it?

**Comment by titicaca** [comment]
What's the version of your spark? This pkg was tested on spark 2.x,
