### ISSUE TITLE
build is getting failed with spark 2.3 version .

### ISSUE THREAD

**Issue by darshoka** [titicaca/spark-iforest#5]

**Comment by darshoka** [comment]
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building spark-iforest 2.4.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spark-iforest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/bizviz/git_dataprep_anomaly_library/dataprep/spark-iforest/src/main/resources
[INFO] 
[INFO] --- scala-maven-plugin:3.3.2:compile (default) @ spark-iforest ---
[INFO] artifact commons-codec:commons-codec: checking for updates from repo1
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  com.twitter:chill_2.11:0.8.4 requires scala version: 2.11.8
[WARNING]  org.apache.spark:spark-core_2.11:2.3.0 requires scala version: 2.11.8
[WARNING]  org.json4s:json4s-jackson_2.11:3.2.11 requires scala version: 2.11.0
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ spark-iforest ---
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.3.2:compile (compile) @ spark-iforest ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  com.twitter:chill_2.11:0.8.4 requires scala version: 2.11.8
[WARNING]  org.apache.spark:spark-core_2.11:2.3.0 requires scala version: 2.11.8
[WARNING]  org.json4s:json4s-jackson_2.11:3.2.11 requires scala version: 2.11.0
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ spark-iforest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ spark-iforest ---
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.3.2:testCompile (test-compile) @ spark-iforest ---
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  com.twitter:chill_2.11:0.8.4 requires scala version: 2.11.8
[WARNING]  org.apache.spark:spark-core_2.11:2.3.0 requires scala version: 2.11.8
[WARNING]  org.json4s:json4s-jackson_2.11:3.2.11 requires scala version: 2.11.0
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.7:test (default-test) @ spark-iforest ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ spark-iforest ---
Discovery starting.
Discovery completed in 1 second, 386 milliseconds.
Run starting. Expected test count is: 7
IForestSuite:
19/02/26 15:25:46 WARN Utils: Your hostname, my-engine resolves to a loopback address: 127.0.0.1; using 192.168.10.209 instead (on interface enp0s25)
19/02/26 15:25:46 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
19/02/26 15:25:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
- default parameters
- set parameters
- split data
- sample features
*** RUN ABORTED ***
  java.lang.NoSuchMethodError: org.apache.spark.ml.util.Instrumentation$.instrumented(Lscala/Function1;)Ljava/lang/Object;
  at org.apache.spark.ml.iforest.IForest.fit(IForest.scala:475)
  at org.apache.spark.ml.iforest.IForestSuite$$anonfun$1.apply$mcV$sp(IForestSuite.scala:107)
  at org.apache.spark.ml.iforest.IForestSuite$$anonfun$1.apply(IForestSuite.scala:97)
  at org.apache.spark.ml.iforest.IForestSuite$$anonfun$1.apply(IForestSuite.scala:97)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.apache.spark.SparkFunSuite.withFixture(SparkFunSuite.scala:67)
  ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:11 min
[INFO] Finished at: 2019-02-26T15:26:07+05:30
[INFO] Final Memory: 29M/401M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project spark-iforest: There are test failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Process finished with exit code 1

**Comment by darshoka** [comment]
please help @titicaca

**Comment by titicaca** [comment]
ML api has changed on spark v2.4.x, 
Try the version v2.3.0 https://github.com/titicaca/spark-iforest/releases/tag/v2.3.0

**Comment by darshoka** [comment]
@titicaca thanks .. i will try with this .

**Comment by darshoka** [comment]
@titicaca It is having some transitive dependency with spark 2.4. automatically downloading 2.4 spark libraries when i used this in a sbt project .

**Comment by darshoka** [comment]
my build.sbt is as follows 

scalaVersion := "2.11.8"

resolvers += Resolver.mavenLocal

libraryDependencies += "com.typesafe.play" % "play-json_2.11" % "2.6.7"

libraryDependencies += "org.apache.spark" %% "spark-core" % "2.3.0"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.3.0"
libraryDependencies += "org.apache.spark" %% "spark-mllib" % "2.3.0"

libraryDependencies += "org.specs" % "specs" % "1.4.0" % Test
libraryDependencies += "org.specs2" %% "specs2-core" % "2.4.16" % Test
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1" % Test

dependencyOverrides += "com.fasterxml.jackson.core" % "jackson-core" % "2.8.9"
dependencyOverrides += "com.fasterxml.jackson.core" % "jackson-databind" % "2.8.9"
dependencyOverrides += "com.fasterxml.jackson.module" % "jackson-module-scala_2.11" % "2.8.9"
libraryDependencies += "com.twitter" %% "util-eval" % "6.43.0"
libraryDependencies += "org.apache.spark.ml" % "spark-iforest" % "2.3.0"

**Comment by titicaca** [comment]
Is there any building error?

**Comment by darshoka** [comment]
@titicaca  No build error . IForestExample running fine . But when i used this library in a sbt project , I am getting following error 

> 19/02/27 10:16:45 INFO DAGScheduler: Job 7 finished: zipWithIndex at IForest.scala:452, took 0.567872 s
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.ml.util.Instrumentation$.create(Lorg/apache/spark/ml/Estimator;Lorg/apache/spark/rdd/RDD;)Lorg/apache/spark/ml/util/Instrumentation;
	at org.apache.spark.ml.iforest.IForest.fit(IForest.scala:480)
	at org.apache.spark.ml.iforest.IForest.fit(IForest.scala:317)
	at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:153)
	at org.apache.spark.ml.Pipeline$$anonfun$fit$2.apply(Pipeline.scala:149)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
	at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:149)

**Comment by titicaca** [comment]
Emm, it looks like a spark version error. Could you double check your spark version and spark-iforest pkg in your sbt project?

**Comment by darshoka** [comment]
I removed my .ivy2 cache , then build again . it start working . 

@titicaca do you have any perfomance report (Time taken to process 1 billion records ) of the algorithm ?

**Comment by darshoka** [comment]
I am closing the issue . thanks

**Comment by blackvvine** [comment]
Hi, I'm getting the same error in version 2.4.0 with Spark 2.4 at **runtime**, although the tests all pass.

```python
iforest = IForest(contamination=0.3, maxDepth=2)
model = iforest.fit(nz_df)
```

Results:

```
Py4JJavaError: An error occurred while calling o161.fit.
: java.lang.NoSuchMethodError: org.apache.spark.ml.util.Instrumentation$.instrumented(Lscala/Function1;)Ljava/lang/Object;
	at org.apache.spark.ml.iforest.IForest.fit(IForest.scala:495)
	at org.apache.spark.ml.iforest.IForest.fit(IForest.scala:334)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

Any ideas what could the problem be?
