### ISSUE TITLE
approxQuantile still asking for exact quantile

### ISSUE THREAD

**Issue by pmarko1711** [titicaca/spark-iforest#6]
First of all, many thanks for this library. I'm trying to use it in my setting, and I got it to work; however, I fail on larger datasets. While investigating I noticed the following: 

Despite using `org.apache.spark.sql.DataFrameStatFunctions.approxQuantile()` I think you still ask for exact quantile in your `transform()`. The reason for that is that you pass 0 as the third parameter (`relativeError`) and thus don't allow for any approximation here. 
```scala
val threshold = scoreDataset.stat.approxQuantile($(anomalyScoreCol),
      Array(1 - $(contamination)), 0)
```

See
[approxQuantile @ spark.apache.org](https://spark.apache.org/docs/2.0.2/api/java/org/apache/spark/sql/DataFrameStatFunctions.html#approxQuantile(java.lang.String,%20double[],%20double)): 
"`relativeError` - The relative target precision to achieve (>= 0). **If set to zero, the exact quantiles are computed, which could be very expensive**. Note that values greater than 1 are accepted but give the same result as 1."

Any chance you would allow parametrizing this `relativeError` in your `IForest`, please?

**Comment by titicaca** [comment]
Thanks for reporting it. I have just added the param named approxQuantileRelativeError, you can checkout the newest codes in the master branch and have a try.

**Comment by pmarko1711** [comment]
Many thanks. I could not test on my side, as I have only spark 2.2.0 at hand. Still, thanks a lot.
